/**
 * This file was generated by the JPA Modeler
 */
package com.eshop.cart.model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

/**
 * @author User
 */
@Entity
public class Product implements Serializable {

    @Column(name = "ID1")
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String description;

    @Basic
    private String retailprice;

    @ManyToMany(targetEntity = ProductOrder.class, mappedBy = "products")
    private List<ProductOrder> productOrders;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getRetailprice() {
        return this.retailprice;
    }

    public void setRetailprice(String retailprice) {
        this.retailprice = retailprice;
    }

    public List<ProductOrder> getProductOrders() {
        return this.productOrders;
    }

    public void setProductOrders(List<ProductOrder> productOrders) {
        this.productOrders = productOrders;
    }

}
